name: Build and push artifacts

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
env:
  HELM_EXPERIMENTAL_OCI: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  reusable_workflow_job:
    uses: MapColonies/shared-workflows/.github/workflows/build-and-push.yaml@master
    secrets: inherit
